env:
  TERM: xterm-256color
window:
  padding:
    x: 10
    y: 10
  dynamic_padding: false
font:
  normal:
    family: Hack Nerd Font #monospace
    style: regular
  offset:
    y: 0
colors:
  name: Lovelace
  author: elenapan
  primary:
    background: "#1d1f28"  #"#21242b"
    foreground: "#fdfdfd"   #"#bbc2cf"
  cursor:
    text: "#21242b"
    cursor: "#bbc2cf"
  normal:
    black: "#282A36"
    red: "#F37F97"
    green: "#5ADECD"
    yellow: "#F2A272"
    blue: "#8897F4"
    magenta: "#C574DD"
    cyan: "#79E6F3"
    white: "#FDFDFD"
    # black: "#1d2026"
    # red: "#ff6c6b"
    # green: "#98be65"
    # yellow: "#ecbe7b"
    # blue: "#51afef"
    # magenta: "#c678dd"
    # cyan: "#46d9ff"
    # white: "#efefef"
  bright:
    black: "#414458"
    red: "#FF4971"
    green: "#18E3C8"
    yellow: "#FF8037"
    blue: "#556FFF"
    magenta: "#B043D1"
    cyan: "#3FDCEE"
    white: "#BEBEC1"
